### ISSUE TITLE
Getting `Cannot read properties of undefined (reading 'addListener')` on ngrok.io subdomain (non-Shopify project)

### ISSUE THREAD

**Issue by vfonic** [ConduciveMammal/theme-explorer#12]
I've got a non-Shopify project that I'm running through Ngrok.

I get this error in dev tools console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'addListener')
    at contentScript.bundle.js:1:462
    at contentScript.bundle.js:1:635
```

**Comment by ConduciveMammal** [comment]
Thanks for the report @vfonic 

This was actually caused by a code change I introduced in the [latest release](https://github.com/ConduciveMammal/theme-explorer/commit/273ff12b29dcc95349e3b1f4a3ed3fee2abab84b).

This code is totally separate from the functionality so that shouldn't be affected at all.
